### ISSUE TITLE
Divide subview by scalar

### ISSUE THREAD

**Issue by palango** [bluss/rust-ndarray#110]
I'm trying to write a simple `mean` function that calculates the mean of an array for a given axis. Looking at `sum` I cam up with the following, but now I can't figure out how to divide the sum by the number of elements. 
If I try normal divison I get: `error: the trait 'core::ops::Div<usize>' is not implemented for the type 'A'`. If I try the `idiv` version it tells me `error: mismatched types:
 expected 'A',
    found 'usize'
(expected type parameter,
    found usize) [E0308]`

Do you have any hints?

```rust
trait Stats<A, S, D>
        where A: Clone + Add<Output = A> + Div<Output = A>,
              D: RemoveAxis
{
    fn mean(&self, Axis) -> OwnedArray<A, <D as RemoveAxis>::Smaller>;
}

impl<A, S, D> Stats<A, S, D> for ArrayBase<S, D>
    where A: Clone + Add<Output = A> + Div<Output = A> + Div,
          S: Data<Elem = A>,
          D: Dimension + RemoveAxis
{
    fn mean(&self, axis: Axis) -> OwnedArray<A, <D as RemoveAxis>::Smaller> {
        let n = self.shape()[axis.axis()];
        println!("{:?}", self.shape());
        let mut res = self.subview(axis, 0).to_owned();
        for i in 1..n {
            let view = self.subview(axis, i);
            res.iadd(&view);
        }
        // res.idiv(&arr0::<A>(n));
        res / n
    }
}
```

**Comment by bluss** [comment]
Hi! That looks very similar to the .mean() that already exists in the library :smile:

What you need is a way to convert the divisor into an element type that you can divide by. If you require for example the trait [Float](http://rust-num.github.io/num/num/traits/trait.Float.html), then that also includes a function to cast a usize to float.

**Comment by bluss** [comment]
Regarding generics for numbers though, I think that area is still in flux in ndarray. It's not so easy to get everything right as one would think.

**Comment by bluss** [comment]
This documentation in ndarray: https://bluss.github.io/rust-ndarray/master/ndarray/trait.ScalarOperand.html

It tries to explain how Array with scalar arithmetic operators are implemented in ndarray.

**Comment by palango** [comment]
Thanks for the hints, will read!

**Comment by bluss** [comment]
I appreciate any feedback. Nothing is perfect in this library yet.

**Comment by bluss** [comment]
I think we need our own numerical traits here eventually. What do you think?

In particular, I think it's desireable to make one trait that basically just captures f32 and f64, and allows all possible ndarray operations. Then the same kind of thing for float and complex together.

**Comment by palango** [comment]
Agree with you! I'm mostly interested in scientific applications, so f32/f64 is the main interest.
