### ISSUE TITLE
Implementing Index<Axis> for Dimension

### ISSUE THREAD

**Issue by vbarrielle** [bluss/rust-ndarray#111]
This would allow using `a.dim()[Axis(0)]`, which is not that much of a win. However, when implementing a method that takes an Axis as an argument, this could be a real win:
`a.dim().slice()[axis.axis()]` vs `a.dim()[axis]`.

What do you think?

**Comment by bluss** [comment]
Sounds good, I'm not sure if coherence will allow us to do this easily? I hope we can keep this an implementation detail.

**Comment by bluss** [comment]
Kind of a side note, but I considered `From/Into` for axis and I think we promote better code if `.subview(0.into(), 0)` is **not** possible.

**Comment by vbarrielle** [comment]
I'll try implementing Index and see how that works out. I agree for the Into impl it's better not to allow this.
