### ISSUE TITLE
New use for the identifier `Array`

### ISSUE THREAD

**Issue by bluss** [bluss/rust-ndarray#145]
Old type alias `Array` is deprecated.

Some shortlist candidates for new use are (A) ArrayBase becomes Array, (B) OwnedArray becomes Array, (C) A new trait is made and called Array.

Any suggestions welcome.

**Comment by jdroenner** [comment]
First i was going to vote for (C) but now i think option (A) is the best use for `Array`. A trait for something that is like an array could be called `ArrayLike`.

**Comment by bluss** [comment]
Thanks for the input. I'm somehow hoping that using ArrayBase in client code can be avoided (and they stick to OwnedArray, ArrayView). But as usual I don't know enough yet :smile:

**Comment by jdroenner** [comment]
So we would need a trait (`Array`) to work with generic arrays (`OwnedArray` or `ArrayView`) without `ArrayBase` in client code?
Maybe `Array` could combine multiple specialized traits to allow implementing generic algorithms (similar to the approach of [ImgLib2](http://imagej.net/ImgLib2_Examples)).

**Comment by bluss** [comment]
or to be generic over something that does not exist yet, for example proposed masked arrays or arrays with various statically known properties
