### ISSUE TITLE
Add method to modify elements in place

### ISSUE THREAD

**Issue by bluss** [bluss/rust-ndarray#153]
A value-to-value mapper would be convenient, something like `array.apply(f32::abs)` it could even be called `lift`.

**Comment by bluss** [comment]
We want to find a nice convention to make it easier to understand.

Maybe something like this, saying map for an operation that makes a new array, and apply for modifying in place. Since all the float functions are by value "`|A| -> A`", it would be important to offer this.


```rust
 .map(&self, |&A| -> B) -> OwnedArray<B, D>
 .mapv(&self, |A| -> B) -> OwnedArray<B, D>
 .apply(&mut self, |&mut A|)
 .applyv(&mut self, |A| -> A)
```

**Comment by jdroenner** [comment]
Maybe the map operations could be lazy like iterator adapters. A `MapView `(or something like this) would have a reference/view of an array and a map function. This would allow to use `get(dim) `without processing the total array first (could be useful for sampling). Also chaining of multiple map operations could be possible. A function like collect could be used to materialize into a new `OwnedArray`. This could also be interesting for #120 or #127.

**Comment by bluss** [comment]
That's a nice idea. It's similar to this https://github.com/bluss/rust-ndarray/issues/88#issuecomment-196971867

Making an operation an object that itself can participate in operations on arrays makes particular sense in an even more generic-heavy implementation. For that reason ndarray will not take that route now, I think.
