### ISSUE TITLE
Papercut: mismatch between name and signature

### ISSUE THREAD

**Issue by daniel-vainsencher** [bluss/rust-ndarray#163]
The name of `from_slice_dim_stride(dim: D, strides: D, xs: &'a mut [A])` suggests a parameter ordering inconsistent with what it actually expects.

Same goes for `pub fn from_vec_dim(dim: D, v: Vec<A>)` and related constructors.

I suggest to change the API now despite the breakage, rather than wait to get more users. I don't have good ideas on which ordering to choose.

**Comment by bluss** [comment]
tricky. Thanks for the report!

**Comment by bluss** [comment]
This mess of constructors makes me think of the only rust idiom that handles it -- the builder pattern. Not sure it's so nice though.

```rust
OwnedArray::new((3, 2)).zeros();
OwnedArray::new((3, 2)).from(vec);
OwnedArray::new((3, 2)).f().from(vec);
OwnedArray::new((3, 2)).strides((3, 1)).from(iterable);
OwnedArray::new((3, 2)).unchecked().from(vec);

```

It composes it down, but I'm not so sure I like it.

**Comment by daniel-vainsencher** [comment]
I don't like it much either. Imo a fancy creation api can wait.

**Comment by bluss** [comment]
Another idea is to put the "decoration" on the dimension type

```rust
OwnedArray::zeros((3, 2))   // zeros
OwnedArray::zeros((3, 2).f())   // zeros_f
OwnedArray::from_vec_dim((3, 2).f(), vec); // from_vec_dim_f
OwnedArray::from_vec_dim((3, 2).strides((3, 1)), vec); // from_vec_dim_strides
```

**Comment by daniel-vainsencher** [comment]
I kind of like the idea of constructing "layout" objects from dimension +
stride information, and then using that in constructing the array. For the
sake of the original bug, though, please change the name so

OwnedArray::from_dim_vec((3, 2).f(), vec);

that is, match the order of arguments with the name of the method. Two
functions seem in order:

OwnedArray::from_dim_vec((3, 2), vec);  // For the simple case
OwnedArray::from_layout_vec((3, 2).strides((3, 1)), vec); // For the
non-default-stride cases

since the first argument is no longer just a dimension.

Daniel

On Wed, Apr 6, 2016 at 9:32 AM, bluss <notifications@github.com> wrote:
>
> Another idea is to put the "decoration" on the dimension type
>
> OwnedArray::zeros((3, 2))   // zeros
> OwnedArray::zeros((3, 2).f())   // zeros_f
> OwnedArray::from_vec_dim((3, 2).f(), vec); // from_vec_dim_f
> OwnedArray::from_vec_dim((3, 2).strides((3, 1)), vec); //
from_vec_dim_strides
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub




--
Daniel Vainsencher
