### ISSUE TITLE
outer_iter bug

### ISSUE THREAD

**Issue by pegasos1** [bluss/rust-ndarray#194]
In a project I'm working on, I had a bug in which `outer_iter` was iterating over the inner axis of a matrix, not outer axis. Changing the iterator to `axis_iter(Axis(1))` fixed bug. 

In iterators.rs, 
```
pub fn new_outer_iter<A, D>(v: ArrayView<A, D>) -> AxisIter<A, D::Smaller>
    where D: RemoveAxis
{
    AxisIter {
        iter: new_outer_core(v, 0),
        life: PhantomData,
    }
}
```

Should the second argument to `new_outer_core` be `1`, not `0`?

**Comment by vbarrielle** [comment]
That looks weird, I've been using `outer_iter` quite a lot and never had any issue. Do you have an example where there's a bug?

**Comment by bluss** [comment]
Axis 0 is the definition of "outer" that it uses. What definition of "outer" did you have in mind?

**Comment by pegasos1** [comment]
Hm, I thought outer_iter traverses columns, and inner iter traverses rows. But either way, here's the test case that reproduces the issue in my code. This test passes, and I thought the assertion in the first loop should fail. Shouldn't inner_iter and outer_iter iterate over different arrays in this case?
 
```
fn test_iter() {
        let rows = 10;
        let cols = 5;

        let x = OwnedArray::random((rows, cols), Range::new(0., 10.));

        for (x, y) in x.inner_iter().zip(x.outer_iter()) {
            assert!(x == y)
        }
        for (x, y) in x.axis_iter(Axis(0)).zip(x.axis_iter(Axis(1))) {
            assert!(x != y)
        }
    }
```

**Comment by bluss** [comment]
inner iter and outer iter have different kinds of definitions, but for the 2 dimensional case they do the same thing. Inner iter always gives one-dimensional array views, outer iter always gives n-1 dimensional array views for an array of dimension n.

**Comment by pegasos1** [comment]
gotcha. might be helpful in the docs to explicitly note that the methods don't generalize to 2 dim case, since it wasn't immediately clear.

**Comment by bluss** [comment]
You are right, that all needs another go at the documentation, with an eye for the whole picture.

**Comment by bluss** [comment]
Thanks for reporting stuff anyway

**Comment by pegasos1** [comment]
for sure!
