### ISSUE TITLE
How to create a 2D ArrayBase or RcArray from a Vec<Vec<f64>>?

### ISSUE THREAD

**Issue by cgarciae** [bluss/rust-ndarray#197]
I am parsing a csv and need to create a matrix, haven't found this in the docs. I've seen rcarr2 but that works with arrays, not vectors.

**Comment by vbarrielle** [comment]
Maybe you can use something like the `stack!` macro to create an OwnedArray, and from there go to an RcArray if that's what you want.

**Comment by bluss** [comment]
I would concatenate it to a single Vec and then call `OwnedArray::from_shape_vec((m, n), v)` where `v` is the single dimensional vector, and `m` the number of rows, `n` the number of columns. The method returns a `Result` and you can use `unwrap` for example to get the array.

**Comment by cgarciae** [comment]
Thanks! Found @bluss by myself last week.
