### ISSUE TITLE
crates.io ?

### ISSUE THREAD

**Issue by mitchmindtree** [bluss/rust-ndarray#2]
Once again, you happen to have just what I need :smile: 

Any chance this will find its way onto crates.io any time soon?

**Comment by mitchmindtree** [comment]
Ohhh, just noticed it's not yet stable.

**Comment by bluss** [comment]
I'm not at home yet, so not much will be done right now, but I'll tell you about the status

- Regard this as a prototype
- Want to find a better performing way for multidimensional iterators
- Currently Arrays are Copy-on-write only, want to offer owned arrays and array views too. Possibly lightweight views (i.e. a slice kind of type).
- I'll put this on crates.io on request, but it will be "unstable/experimental" even if we find a subset that compiles on the stable channel.
- It helps if you tell about your requirements
  - Linear algebra or generic multidim container?
  - Sharing or owned + views?
  - Other

**Comment by bluss** [comment]
It builds on beta, so it can be stable in Rust 1.4.

**Comment by mitchmindtree** [comment]
:+1:

**Comment by bluss** [comment]
on crates.io as rendarray
