### ISSUE TITLE
Any planned support for inverse and covariance?

### ISSUE THREAD

**Issue by rigdent** [bluss/rust-ndarray#201]
Hello,

First thanks for making an repo that supports nd arrays! I was wondering if there is any planned support for getting the inverse and for getting the covariance matrix of an ndarray? I am trying to implement a mahalanobis distance in rust. 

Thanks!

**Comment by bluss** [comment]
Obviously the linear algebra plan hasn't brought much to the table yet.

The loose plan is that: Provide inverse etc by integrating with lapack. Initially we don't plan any fallback (pure Rust) implementations but instead require lapack for these features. This unless we can produce high quality impls in Rust ourselves (or link to them using cargo).

**Comment by rigdent** [comment]
Ok. Thanks for the quick response!
