### ISSUE TITLE
Better ergonomics for index types

### ISSUE THREAD

**Issue by b52** [bluss/rust-ndarray#202]
Currently, it's a pain in the ass to work with the index types in a somewhat generic way at runtime. There is no comparison to, e.g., numpy. One very trivial example: given a matrix, a position and an offset, access the field at position + offset. Now do this for arrays of arbitrary dimensionality.

To ease the work with the index type I propose (1) to define a new trait with useful bounds to allow arithmetic operations with index types and (2) to provide and use new-type wrappers for most common dimensionalities throughout ndarray:

```rust
pub trait Ix: Add + ... {}
```

This way one can write generic code for arrays of arbitrary dimensionality, assuming the above given example:

```rust
fn increment<I: Ix>(array: &mut ArrayViewMut<f32, I>, position: I, offset: I) {
    array[position + offset] += 1.0;
}
```

Use new-type implementation of this trait to support most common dimensionalities

```rust
pub struct Ix1([usize; 1]);
...
```

with proper `Into` and other useful implementations.

I left out most of the details just to get an unbiased discussion started. I like ndarray, but it's static nature (compared to, e.g., numpy) makes it currently hard to work with in a pleasant way.

Additionally, `ndarray` should provide type aliases for the most common arrays as well, to ease the development and mental load while parsing code:

```rust
type Array1<D> = Array<D, Ix1>;
...
```

**Edit:** It might make sense to use these types for the shape as well.

**Comment by bluss** [comment]
```rust
fn increment<I: Ix>(array: &mut ArrayViewMut<f32, I>, position: I, offset: I) {
    array[position + offset] += 1.0;
}
```

Since it needs to define `+` on the index type, we can't continue using tuples or fixed size arrays. To allow that we would require something like this:

```rust
fn increment<I: IntoIndex>(array: &mut ArrayViewMut<f32, I::Index>, position: I, offset: I) {
    array[position.into() + offset.into()] += 1.0;
}
```

which is "not good enough" to motivate the change, we could shoot for better somehow..

**Comment by b52** [comment]
Could you elaborate why it is "not good enough"? There is a legit reason for `Into` and `From`, especially in combination with new-type wrappers.

**Comment by bluss** [comment]
Using .into() everywhere is not ergonomics
