### ISSUE TITLE
rows and cols methods need to return usize and not Ix

### ISSUE THREAD

**Issue by Kerosene2000** [bluss/rust-ndarray#205]
... because that's not an `Index type` but `a quantity`.
https://bluss.github.io/rust-ndarray/master/ndarray/struct.ArrayBase.html#method.rows
https://bluss.github.io/rust-ndarray/master/ndarray/struct.ArrayBase.html#method.cols

**Comment by bluss** [comment]
Thank you. It doesn't make any technical difference, but we can do this.

**Comment by Kerosene2000** [comment]
Do you want me to make a PR ?

**Comment by bluss** [comment]
Sure

**Comment by Kerosene2000** [comment]
https://github.com/bluss/rust-ndarray/pull/206
