### ISSUE TITLE
Implement ToOwned for ArrayBase

### ISSUE THREAD

**Issue by CryZe** [bluss/rust-ndarray#208]
No idea why to_owned is just a normal method on ArrayBase instead of a proper ToOwned impl. I can't use Cow with the ArrayViews now :(

**Comment by SuperFluffy** [comment]
Isn't that the idea behind having `RcArray`? I quote from the docs:

> `RcArray`: An array where the data has shared ownership and is copy on write.

**Comment by CryZe** [comment]
From what I can tell, it doesn't seem appropriate for the use case I'm dealing with. I'm getting an ArrayView<T> as my parameter and potentially need to clone the data and then I need to work with either the clone or the view depending on the case. And it doesn't look like I can turn the ArrayView into a RcArray without cloning the data.

**Comment by bluss** [comment]
We can't use the libstd `ToOwned` trait for several reasons, including that array views already fall under the blanket libstd 'ToOwned` implementation that uses .clone(). It's really only usable in a separate way for built in DST "view" types like `str` and slices, not like ArrayView which is not a DST.

**Comment by bluss** [comment]
Closing since technically ArrayBase implemlent `ToOwned`, and there's not much more we can do about it. The relevant implementation line is `impl<T> ToOwned for T where T: Clone` in the docs: https://doc.rust-lang.org/std/borrow/trait.ToOwned.html
