### ISSUE TITLE
QUESTION: ArrayView into C allocated memory

### ISSUE THREAD

**Issue by fkjogu** [bluss/rust-ndarray#209]
I'm trying to do a 2D Fourier transform calling to [FFTW3](www.fftw.org) over FFI. For internal performance reasons, FFTW3 offers a custom malloc function, that returns a pointer to a RowMajor C-array.

Can I somehow bind this to an ndarray ArrayView?

Please feel free to close the issue, since it is more a question than an issue.

**Comment by vbarrielle** [comment]
Unfortunately, it looks like `ArrayView::new_` is private, even though you could use it for that purpose.
@bluss, if you want I can put it public (under a more explicit name maybe) and PR.

**Comment by bluss** [comment]
You can use the existing aview1, ArrayView::from or ArrayView::from_shape(shape, slice), if you combine them with std::slice::from_raw_parts.

We can add separate direct constructors though.

**Comment by vbarrielle** [comment]
Oh right, I didn't think of creating the slice first...

> We can add separate direct constructors though.

I do think it would be nice, since interfacing with C allocated arrays might be frequent if people want to e.g. interface with numpy. I'll PR a direct constructor so you can tell me what you think.
