### ISSUE TITLE
Add PartialOrd impls

### ISSUE THREAD

**Issue by bluss** [bluss/rust-ndarray#22]

**Comment by spencerlyon2** [comment]
What struct(s) should this be implemented for? I would like to take a stab a this

**Comment by bluss** [comment]
To start with, like `PartialEq` does it. Then possibly expand to mismatching dimension parameters and broadcasting later. I'd keep it simple first.

**Comment by bluss** [comment]
Oh `PartialEq` simply says `false` for unequal shapes. We can't really translate that to PartialOrd (except using partiality, but that doesn't affect the comparison operators..). Maybe returning None in `partial_cmp` method for unequal sizes, and panicking in the lt, etc methods will be ok?

**Comment by bluss** [comment]
See `src/arraytraits.rs` line 60.

**Comment by spencerlyon2** [comment]
How could I return None in `partial_cmp`? 

Isn't the signature:

```rust
fn partial_cmp(&self, other: &Rhs) -> Option<Ordering>;
```

**Comment by bluss** [comment]
Yes, `Option` admits `None`. Maybe you see better what makes sense while implementing it.

**Comment by spencerlyon2** [comment]
Ahh, I get it. Sorry. First real experience with rust. Working on it now. Should have a PR ready soon.

**Comment by spencerlyon2** [comment]
Ok I think I have something that makes some sense, but I think I could use some feedback.

```rust
impl<S, S2, D> PartialOrd<ArrayBase<S2, D>> for ArrayBase<S, D>
    where D: Dimension,
          S: Data,
          S2: Data<Elem = S::Elem>,
          S::Elem: PartialOrd,
{
    /// Return `None` if the array shapes `self` and `rhs` are not equal.
    /// Return appropriate `Option<Ordering>` otherwise.
    fn partial_cmp(&self, rhs: &ArrayBase<S2, D>) -> Option<Ordering>
    {
        // Balk on arguments with different shapes. Should probably
        // broadcast at some point
        if self.shape() != rhs.shape() {
            return None;
        }
        // Use partial_cmp from the slice version if contiguous
        if let Some(self_s) = self.as_slice() {
            if let Some(rhs_s) = rhs.as_slice() {
                return self_s.partial_cmp(rhs_s);
            }
        }

        let mut cmps = self.iter().zip(rhs.iter()).map(|(a, b)| a.partial_cmp(b));
        let first_cmp_opt = cmps.next();
        if let Some(first_cmp) = first_cmp_opt {
            if cmps.all(|x| x == first_cmp) {return first_cmp}
        }
        None
    }
}
```

Any comments or thoughts?

**Comment by bluss** [comment]
## PartialOrd semantics for ndarray

- There is no precedent for array-wise (not elementwise) comparison operators in numpy. There is array equality and equivalency (broadcasts), but no less than etc relations

- Challenges
  - Shape mismatch
  - Shape mismatch where broadcasting does not solve it
  - Float comparison with NaN returns `None` for `.partial_cmp()` but `false` for all other comparisons. Returning `false` when incomparable is a bit like letting errors pass silently.

- Approach 1: Lexicographical ordering
  - `&[T]` does this. Different length is no problem
  - For one-dimensional ndarrays we have no problem to mimic this. But for higher dimensional? Implicitly comparing every array pair by their corresponding unravelled one dimensional sequence is not very intuitive.

- Approach 2: Every element is less (or le, gt, ge), otherwise the comparison is false
  - Still has shape mismatch issues

Panic on shape mismatch would be the alternative to letting errors pass silently in `<` comparison, but it's also a nasty surprise.

**Comment by bluss** [comment]
Summary above is good, we simply hold this off since it seems there are no good semantics.
