### ISSUE TITLE
Creating Array with closure and shape

### ISSUE THREAD

**Issue by WaDelma** [bluss/rust-ndarray#221]
It would nice if there was a way to create new Array with closure: I am currently creating Array with zeros and then going through it setting values.

I imagining function like this:
````rust
fn from_fn<F, Sh>(Sh, F) -> ArrayBase<S, D>
  where Sh: Into<Shape<D>>,
        F: Fn(D) -> A
````

**Comment by bluss** [comment]
Sounds good to me

**Comment by bluss** [comment]
Do you need access to the indices?

**Comment by WaDelma** [comment]
Yeah I do.

**Comment by bluss** [comment]
This has been added in master

**Comment by bluss** [comment]
In version 0.6.6.
