### ISSUE TITLE
Implement ExactSizeIterator

### ISSUE THREAD

**Issue by jplatte** [bluss/rust-ndarray#226]
Hi, I was wondering if it would be possible / desired to implement `ExactSizeIterator` for `*_iter()` and `*_iter_mut()`. I haven't looked at the code base yet, but I'd take a stab at making a PR if so.

**Comment by bluss** [comment]
Sure I think so, which iterator doesn't already implement it?

Curiosity: Why do you need it?

**Comment by jplatte** [comment]
`indexed_iter()` doesn't implement it. I need it because in a game I'm writing, I have a bunch of map parts structured in a way that is well-suited for the map generated that I then slurp up into one big iterator for easier processing in the rendering loop (which wants to know the amount of elements it renders before the fact to allocate a buffer).

**Comment by bluss** [comment]
sounds good. Since it should have the same size logic as the Elements / Baseiter iterators, it should be very simple. If you find a simpler way to compute the size hint, that's welcome too.

**Comment by jplatte** [comment]
Hmm, now that I've had a closer look at `ExactSizeIterator`...

> This method has a default implementation, so you usually should not implement it directly.

I assume that means it will use the lower bound from `size_hint()`? So yeah, will have a look at the implementation of that for all the Iterator types and implement `ExactSizeIterator` as fit.

**Comment by bluss** [comment]
It's not going to be a lot of typing. :smile: All the work is ensuring that the impl is actually correct (is the size hint always exact?)

There should already be a test that checks this for the elements iterator.

**Comment by jplatte** [comment]
Huh, so `Indexed` and `IndexedMut` are actually the only iterators that don't implement `ExactSizeIterator`.. Am I misunderstanding something here? I feel like this should be a no-brainer, since with those iterators, you iterate over every single element, just like with `Elements` and `ElementsMut`, no?

**Comment by bluss** [comment]
it's just an oversight, or it wasn't needed
