### ISSUE TITLE
MOLAP design via ndarray

### ISSUE THREAD

**Issue by dankor** [bluss/rust-ndarray#233]
Probably a stupid question. 

Is it possible to create MOLAP cubes using ndarray? Recently I started to discover Rust and came up with that idea to run my first Rust project.

I wonder if there is any documentations around this topic. I'm sorry if I've posted to the wrong place.

**Comment by bluss** [comment]
You'll need to find someone who knows both MOLAP and ndarray to answer the question. https://en.wikipedia.org/wiki/Online_analytical_processing   Maybe a wider forum is better?

**Comment by bluss** [comment]
I'd try http://users.rust-lang.org/
