### ISSUE TITLE
ZST soundness challenge

### ISSUE THREAD

**Issue by bluss** [bluss/rust-ndarray#234]
Find an ndarray test that fails if it is rewritten to use ZST (Zero sized type) array elements. For example the value `()`. If you find one, report a bug.

**Comment by floatn** [comment]
Not sure if it's a ZST problem,
```Rust
let v1 = Vec::<i32>::new();
let A = Array::<i32, _>::from_elem((), 1i32);
let B = Array::<i32, _>::from_vec(v1);
```
println gives different value and size for those two.

**Comment by bluss** [comment]
@floatn Thanks for looking into this. That's expected, `()` is the dimension description for a 0-dimensional array (always has 1 one element ~ isomorphic with a scalar). So it's expected that `A` and `B` both have `.len()` one, but `A` has ndim 0 and `B` has ndim 1.

This issue is for ZST array elements (the element type is `i32` which is not a ZST in your snippet).

**Comment by floatn** [comment]
Guess I get it a bit better now. So, the right way to construct ZST Array is like this?
```Rust
let A = Array::<(), _>::from_elem((), ());
```
Also, shouldn't `size_of_val()` return 0 for a ZST?

**Comment by bluss** [comment]
yes. `size_of_val(&())` should be zero yes.

`Array3::<()>::default((2, 3, 4));` is an array of zst elements, too.

**Comment by bluss** [comment]
And one can make new such types easily of course:

```rust
struct Empty;
```

**Comment by floatn** [comment]
thread 'test_swap' panicked at 'attempt to divide by zero', src/data_traits.rs:127
```Rust
#[test]
fn test_swap() {
    let mut a = arr2(&[[();3];3]);

    let b = a.clone();

    for i in 0..a.rows() {
        for j in i + 1..a.cols() {
            a.swap((i, j), (j, i));
        }
    }
    assert_eq!(a, b.t());
}
```

**Comment by bluss** [comment]
You found something, thanks, that's a bug!

**Comment by floatn** [comment]
one more 'division by size' at 'src/data_traits.rs:93'
```Rust
let C = RcArray::<(), _>::default((3, 4));
let mut D = C.clone();
for _ in D.iter_mut() {}
```

**Comment by bluss** [comment]
Thank you. Fixed in master

**Comment by bluss** [comment]
Ok, we consider this fixed now, new bugs can be reported if any are found.
