### ISSUE TITLE
Replace ArrayBase::assign_scalar with ArrayBase::fill

### ISSUE THREAD

**Issue by bluss** [bluss/rust-ndarray#235]
Is the shorter name worth it? The longer name has some consistency (but not much).

cc @SuperFluffy  I heard you wanted to change .assign_scalar. My suggestion is to just deprecate it (without changing it), and adding .fill() instead, that has the signature that you wanted.

**Comment by SuperFluffy** [comment]
I had hoped you didn't read what I wrote on IRC. :D

I confused the `Clone` restriction in `.assign_scalar` with `Copy`. I think calling it `.assign_element` might be more generic. I don't really have an opionion about `.fill`. I like that `.assign_element` (or `_scalar`) is so verbose. When I was looking for a function like this it was through `assign` that I found what I was looking for.

I guess `.fill` works well too.

**Comment by bluss** [comment]
Why do you like that it's so verbose? What madness is this :smile:

**Comment by bluss** [comment]
I forgot that all the other _scalar methods that it used to be consistent with are gone. There used to be `.iadd_scalar(&1.)` and so on (Replaced by `+=` fortunately).

**Comment by SuperFluffy** [comment]
Well, how often do you set all elements of an array to a specific value? My thought is that the less common an operation is, the more verbose it should be.

Hm, the consistency I was thinking of was with the `AddAssign`, `DivAssign` traits. Unfortunately, we don't have the `Assign` trait just yet. :P

**Comment by bluss** [comment]
Right. We will hopefully have `IndexAssign` in the future. And your reminder is good, that the assign traits are the replacements. They are relevant because of the lvalue rules.

Have you noticed this is not legal code?

```rust
array.slice_mut(s![.., ..;2]) += 1.;
```

Because one can't assign to a temporary value unfortunately.

Anyway, I think fill / assign scalar is a pretty common operation.

**Comment by bluss** [comment]
The workaround is either

```rust
use std::ops::AddAssign;
array.slice_mut(s![.., ..;2]).add_assign(1.);

// or
*&mut array.slice_mut(s![.., ..;2]) += 1.;
```

**Comment by SuperFluffy** [comment]
Aha, interesting. I haven't noticed yet, but this is good to keep in mind.

I get it the issue is `ViewMut` vs `&mut`? There is definitely some overlap there. There are many functions where one needs to pass in a `&mut ViewMut`, which technically doesn't make a lot of sense: I am not interested in mutating the view, I am interested in mutating the things that the view is pointing at... But I don't see a way around this.
