### ISSUE TITLE
Can't compile 0.2.0 

### ISSUE THREAD

**Issue by burrbull** [bluss/rust-ndarray#26]
Compilling ndarray stopped with error 
.cargo/registry/src/github.com-0a35038f75765ae4/ndarray-0.2.0/src/arrayformat.rs:46:23: 46:34 error: no method named `alternate` found for type `&mut core::fmt::Formatter<'_>` in the current scope
.cargo/registry/src/github.com-0a35038f75765ae4/ndarray-0.2.0/src/arrayformat.rs:46                 if !f.alternate() {

Ubuntu 15.04
rust 1.4

**Comment by bluss** [comment]
Aha, thanks for the report! Ndarray requires Rust 1.5, so that's the reason for the error.
