### ISSUE TITLE
rcarr1 should be included in ndarry::prelude

### ISSUE THREAD

**Issue by termoshtt** [bluss/rust-ndarray#261]
I found `rcarr{1,2,3}` are not belong to `ndarray::prelude` while `arr{1,2,3}` are.
Is it as you intended? I think they should be included in `prelude` submodule.

**Comment by bluss** [comment]
Hi, thank you for this issue. RcArray is getting less attention since I don't think it's used much. You have a point about consistency, but at the time I thought rcarr was too special case to include.

**Comment by termoshtt** [comment]
Thanks reply, and I understand the reason.

FYI, I am testing RcArray as clone-on-write storage in my [ode-solver](https://github.com/termoshtt/ndarray-odeint). If I find RcArray is much useful, I will tell you.

**Comment by bluss** [comment]
That's good. I haven't used it since the introduction of the array/view split actually. Your feedback is valuable, feel free to open more issues about rcarray.
