### ISSUE TITLE
`as_slice` vs `into_slice`: inconsistent naming?

### ISSUE THREAD

**Issue by SuperFluffy** [bluss/rust-ndarray#262]
Is there some inconsistency in the naming of `as_slice` (implemented for all `ArrayBase`), and `into_slice` (implemented for those `ArrayBase` where the data is a `ViewRepr`)?

The functions do exactly the same.

Since `as_slice` seems to apply to views as well, I believe `into_slice` could be removed?

**Comment by bluss** [comment]
They have different behaviour, and they exist because that borrowing behaviour has been useful.

Given `&'a ArrayView<'b, T>`, `as_slice` makes a `&'a [T]`. Given `ArrayView<'b, T>`, into_slice makes a `&'b [T]`

**Comment by SuperFluffy** [comment]
Alright, thanks for the clarification, this makes sense. I didn't notice that in `pub fn into_slice(&self) -> Option<&'a [A]>` `self` will have a different lifetime than `'b`.

**Comment by bluss** [comment]
Np. some cleanup is needed here and there. I think we need more rather than fewer into_slice kind of methods for views, unfortunately. (For example .into_axis_iter)
