### ISSUE TITLE
Clone of wrapper struct around `ArrayBase<S: DataClone, D: Dimension>` fails

### ISSUE THREAD

**Issue by SuperFluffy** [bluss/rust-ndarray#263]
I wrap `ArrayBase` and derive `Clone` for the wrapping struct. Even though `derive` seems to happily derive `Clone`, the compiler throws errors when trying to actually execute the clone. See the following example:

```rust
extern crate ndarray;

use ndarray::prelude::*;
use ndarray::DataClone;

#[derive(Clone)]
struct Wrapper<S,D>
where S: DataClone,
    D: Dimension
{
    array: ArrayBase<S,D>,
}

impl<S: DataClone, D: Dimension> Wrapper<S,D> {
    fn attempt_clone(&self) {
        (*self).clone();
    }
}
```

This throws the error:

```
error: no method named `clone` found for type `Wrapper<S, D>` in the current scope
  --> src/main.rs:16:17
   |
16 |         (*self).clone()
   |                 ^^^^^
   |
   = note: the method `clone` exists but the following trait bounds were not satisfied: `S : std::clone::Clone`
   = help: items from traits can only be used if the trait is implemented and in scope; the following trait defines an item `clone`, perhaps you need to implement it:
   = help: candidate #1: `std::clone::Clone`
```

Any idea why this might happen? We have `impl<S: DataClone, D: Clone> Clone for ArrayBase<S, D>` after all. Demanding `S: Clone + DataClone` fixes it, but I don't see why it should be necessary.

**Comment by bluss** [comment]
`S: Clone` is the wrong bound and derive doesn't do the right thing for you here. It's not weird, derive's recipe isn't always the correct one for all structs. I would drop DataClone on the struct and impl Clone manually (unfortunately).

**Comment by SuperFluffy** [comment]
Good point, thanks for the clarification. I realize now that `derive(Clone)` doesn't look at whether the actual *fields* are clonable, but whether the type parameters are. This makes a lot of sense.
