### ISSUE TITLE
Support for Sparse Arrays

### ISSUE THREAD

**Issue by hollinwilkins** [bluss/rust-ndarray#273]
Hey there, great project, thank you for all the hard work on this.

I am wondering if there is any planned support for sparse array data? We are currently in the planning stages of implementing [mleap](https://github.com/combust/mleap) in Rust and need to support both sparse and dense data.

Thank you again!

**Comment by bluss** [comment]
The work I know about is https://github.com/vbarrielle/sprs I don't look like I can commit to working on sparse arrays at this point.

I'm very open to working with ndarray and consumers of it, in the way of extending it in terms of integration features (access to raw details of the data structure) or features closely related to the current feature set.

**Comment by vbarrielle** [comment]
Hello @hollinwilkins, I'm the author of the sprs library @bluss mentionned. I'd be glad if the library can help, but it's still in its early days. I try to make the library compatible with ndarray (eg sparse/dense products). Feel free to open issues in the sprs repo if you have any issue/question.

**Comment by bluss** [comment]
hi @vbarrielle. I'm about to release ndarray 0.8 unfortunately, for serde 0.9.

**Comment by vbarrielle** [comment]
No problem, I'm close to releasing a breaking change to sprs too, so it's a nice occasion for me to syncrhonize these changes.

**Comment by bluss** [comment]
great, then I'll speed up rather than drag the feet for that. :)

**Comment by hollinwilkins** [comment]
@vbarrielle Does your library support broadcasting sparse/dense multiplies and dot products?

**Comment by vbarrielle** [comment]
@hollinwilkins if you mean eg multiplying a sparse matrix by a 1-dim ndarray vector, then yes that works. However apart from this there is no support for broadcasting in sprs. But that could change. What kind of operations would you need?

**Comment by bluss** [comment]
Ok, keep https://github.com/bluss/rust-ndarray/issues/273#issuecomment-283743192 in mind and please report well scoped issues on this topic.
