### ISSUE TITLE
Performance of parallel iterators

### ISSUE THREAD

**Issue by SuperFluffy** [bluss/rust-ndarray#277]
I have implemented a Gram Schmidt orthonormalization using `ndarray-parallel`, but it looks like the implementation's performance had not improved at all. See the benches in https://github.com/SuperFluffy/gram_schmidt/tree/parallel.

The parallelization only happens at one point: https://github.com/SuperFluffy/gram_schmidt/blob/parallel/src/parallel.rs#L58, and for comparison this is the equivalent sequential implementation https://github.com/SuperFluffy/gram_schmidt/blob/parallel/benches/projection_order.rs#L35 (note, the sequential version in the library itself is a bit different, but this one is more amenable to parallelization). What this essentially does is take the vector `v`, calculate the scalar product `c_i` with every single row `w_i` in `todo`, and subtract `c_i * v` from each `w_i`.

When benchmarking this all cores will be completely occupied (4 in my case), but you don't actually win anything, in fact for a 1024x1024 matrix:

```
test parallel ... bench: 564,230,927 ns/iter (+/- 23,454,612)
test project_first ... bench: 590,426,518 ns/iter (+/- 2,687,991)
test project_late  ... bench: 496,520,833 ns/iter (+/- 34,034,300)
```

So this is pretty grim... Any idea where to start looking for the culprit? Is it the algorithm, rayon, or the parallel traits?

**Comment by bluss** [comment]
First thing, try switching to one thread per core (factor out hyperthreading).

**Comment by SuperFluffy** [comment]
That didn't really affect a lot (`echo 0 > /sys/devices/system/cpu{1,3}/online`):

```
test parallel ... bench: 515,717,385 ns/iter (+/- 7,367,157)
test parallel ... bench: 523,230,074 ns/iter (+/- 7,179,283)
```

Looks like disabling hyperthreading did something, but that is still not really cutting it. Is there a chance this could have something to do with the reference to the mutable view `&v` inside the `for_each`?

**Comment by bluss** [comment]
I was thinking of just changing the rayon configuration to use half as many threads (if applicable)

```rust
fn set_threads() {
    let n = max(1, num_cpus::get() / 2);
    let cfg = rayon::Configuration::new().set_num_threads(n);
    let _ = rayon::initialize(cfg);
}
```


I haven't looked so much at the code. If `todo` is row major (ndarray default), then the `axis_iter_mut(Axis(0))` should split the array in the best way (largest stride) so that is not a problem.

Your `zip_mut_with` is identical to `w.scaled_add(-projection_factor, &v)` I think, but the difference is only syntactical (so far), they both use the same code.

**Comment by SuperFluffy** [comment]
`todo` is indeed row-major. I am wondering if there is a way of checking how many threads really run in parallel, i.e. to see if maybe they are all sitting in the pipeline and only get executed once another one is finished.

**Comment by bluss** [comment]
Oh yeah, we haven't experimented with rayon's weights. I don't remember what their current default is.

https://docs.rs/rayon/0.6.0/rayon/par_iter/trait.ParallelIterator.html#method.weight

**Comment by bluss** [comment]
In my understanding there's no invisible synchronization in rayon. As in, the content of the closure doesn't matter. If it compiles, the closure is compatible with fully concurrent execution.

**Comment by SuperFluffy** [comment]
The parallel speed-up is real! I suspect that the 1024x1024 on my laptop CPU might be too big for it to handle. I am going to run another test, but I think it might be too much for its cache, killing the parallel performance. On the other hand, a bigger Xeon is quite happy. :-)

Also, Hyperthreading is abysmal and absolutely destroys performance.

Some more tests:

```
running 3 tests (with hyperthreading)
test parallel__512                 ... bench: 183,319,334 ns/iter (+/- 51,300,917)
```

Compare that to running it with only two cores, `rayon::Configuration::new().set_num_threads(2);` (my CPU has 2 physical and 2 virtual cores):

```
running 3 tests (without hyperthreading)
test parallel__512                 ... bench:  44,777,137 ns/iter (+/- 1,100,552)
test sequential_project_first__512 ... bench:  57,287,434 ns/iter (+/- 849,670)
test sequential_project_late__512  ... bench:  53,621,839 ns/iter (+/- 4,448,999)
```

And this is on a machine with 4 physical + 4 virtual cores; with hyperthreading:

```
test parallel_1024                 ... bench: 816,116,270 ns/iter (+/- 130,648,374)
```

And without:

```
test parallel_1024                 ... bench: 111,277,148 ns/iter (+/- 20,056,107)
test sequential_project_first_1024 ... bench: 309,413,420 ns/iter (+/- 390,392)
test sequential_project_late_1024  ... bench: 287,684,200 ns/iter (+/- 189,023)
```

**Comment by SuperFluffy** [comment]
Some more points for my machine (i7-5500u):

```
test parallel__256                 ... bench:   7,571,569 ns/iter (+/- 228,483)
test sequential_project_first__256 ... bench:   6,490,139 ns/iter (+/- 50,626)
test sequential_project_late__256  ... bench:   6,128,571 ns/iter (+/- 18,853)

test parallel__512                 ... bench:  43,729,553 ns/iter (+/- 3,336,385)
test sequential_project_first__512 ... bench:  54,399,086 ns/iter (+/- 615,809)
test sequential_project_late__512  ... bench:  50,385,446 ns/iter (+/- 400,944)

test parallel__768                 ... bench: 144,790,421 ns/iter (+/- 7,424,019)
test sequential_project_first__768 ... bench: 189,654,592 ns/iter (+/- 1,191,695)
test sequential_project_late__768  ... bench: 175,880,194 ns/iter (+/- 1,499,359)

test parallel_1024                 ... bench: 540,548,667 ns/iter (+/- 3,886,780)
test sequential_project_first_1024 ... bench: 607,676,927 ns/iter (+/- 11,712,223)
test sequential_project_late_1024  ... bench: 514,475,091 ns/iter (+/- 6,418,569)
```

So as we can see there is a speedup, but for 256x256 the matrices are most likely too small for parallelization to matter, and for 1024x1024 I suspect that the matrices get too big for my processors cache.

Note: `sequential_project_first_*` is the sequential version of `parallel_*`.
