### ISSUE TITLE
Implement general_matvec_mul

### ISSUE THREAD

**Issue by Robbepop** [bluss/rust-ndarray#289]
As far as I can imagine ndarray's [general matrix multiplication](http://bluss.github.io/rust-ndarray/master/ndarray/linalg/fn.general_mat_mul.html) is based on [this](https://crates.io/crates/matrixmultiply) crate which has very generalized parameters.

The ndarray `general_mat_mul` function only works for 2-dimensional arrays (matrices) but it should be pretty easy to provide a `general_matvec_mul` function for matrix-vector-multiplication of a **n**x**k** Matrix and a **k**-sized Vector that is reinterpreted under the hood as a **k**x**1** Matrix. The returned **n**x**1** Matrix should be returned as **n**-sized Vector.

```rust
pub fn general_matvec_mul<A, S1, S2, S3>(
        alpha: A,
        a: &Array2<S1, Ix2>,
        b: &Array1<S2, Ix1>,
        beta: A,
        c: &mut Array1<S3, Ix1>)
    where
        S1: Data<Elem=A>,
        S2: Data<Elem=A>,
        S3: DataMut<Elem=A>,
        A: LinalgScalar
```

**Comment by bluss** [comment]
I'm not sure it's a good idea to use the matrix mul for this. For big enough arrays maybe it's faster anyway.

“this” crate :smile: (Which I wrote) uses a packing strategy. One feature of that is that the two matrices are blocked and padded with zeros to fill the size of the kernel (Which is from 4x4 to 8x8). That basically means that the single column vector turns into a 4 or 8-column one.

I think generally you'd use different algorithms. matrix-matrix multiplication uses O(n³) operations on O(n²) data, and matrix-vector multiplication uses O(n²) operations on O(n²) data. My rough understanding is that the high number of operations in m-m multiplication means that it is possible for something else than simply memory bandwidth to limit the speed of the operation. That's all about how they work on a large scale, though.

**Comment by bluss** [comment]
general mat-vec mul should certainly exist, just maybe with a different implementation.

There are already two linalg crates:

- https://crates.io/crates/ndarray-linalg
- https://crates.io/crates/linxal

and ndarray itself is living up pretty badly to its promise of integrating BLAS, but these two crates above help.

**Comment by Robbepop** [comment]
Thanks for those links!

It seems to me that both, ndarray-linalg and linxal, haven't support for mat-vec or even mat-mat multiplication directly - maybe I am just blind.

The question for me is whether you think it is a good idea to provide a mat-vec-mul in ndarray itself.

**Comment by bluss** [comment]
It should. It already exists, but it should exist in the general form too (that outputs to an existing vec).

**Comment by bluss** [comment]
Since we have azip I wonder how far away it's from being adequate

```rust
azip!(mut c, ref a (a.axis_iter(Axis(0))) in { *c = a.dot(&b) });
```

(Not sure what this leaves to improve, maybe lifting out the size check of the dot operation, if the compiler doesn't already do that, and maybe the loop is not so efficient).

I'm curious if there's some published knowledge about the best algorithm to do for this and if there's anything to gain from something sophisticated.
