### ISSUE TITLE
Implement PartialEq for Array and Elem type

### ISSUE THREAD

**Issue by Robbepop** [bluss/rust-ndarray#294]
Currently to check if all elements of an array are `0.0` you have to type something like

```rust
	assert!(arr.iter().all(|&x| x == 0.0));
```

Compared to:
```rust
	assert!(arr == 0.0);
	// or
	assert_eq!(arr, 0.0);
```

This could also lead to small performance improvements and could easily extend to a parallel solution.

**Comment by bluss** [comment]
Right, I'd be a bit wary of overloading equality.

We currently have a “strict” interpretation of equality to be that only arrays of the same dimensions and all elements equal. For example, no broadcasting or other expanded sense of equivalence.

(Note to other observers: `==` in Rust always has a boolean result).

**Comment by bluss** [comment]
I'm going to close this issue. I think you have a very good point and good goal, something about making comparisons with scalars easier. Closing since this way is not how I would like to solve it.

The impl is not even allowed:

```rust
impl<S, A, D> PartialEq<A> for ArrayBase<S, D>
    where D: Dimension,
          S: Data<Elem=A>,
          A: PartialEq
{
    fn eq(&self, rhs: &A) -> bool {
        panic!()
    }
}
```
```rust
error[E0119]: conflicting implementations of trait `std::cmp::PartialEq<ArrayBase<_, _>>` for type `ArrayBase<_, _>`:
   --> src/arraytraits.rs:117:1
    |
91  |   impl<S, S2, D> PartialEq<ArrayBase<S2, D>> for ArrayBase<S, D>
    |   - first implementation here
```

Rust doesn't take into account that an array can't have its own type as element type.
