### ISSUE TITLE
Update to Serde 1.0

### ISSUE THREAD

**Issue by dtolnay** [bluss/rust-ndarray#314]
Release notes: https://github.com/serde-rs/serde/releases/tag/v1.0.0

**Comment by bluss** [comment]
Fixed in ndarray 0.10.0

**Comment by SuperFluffy** [comment]
Note that `num-complex` as of version `0.1.39` is currently not compatible with `serde 1.0`.

Support for it is part of their `0.2` milestone: https://github.com/rust-num/num/issues/281

**Comment by bluss** [comment]
@SuperFluffy That's quite an oversight on my part -- but it's still possible we can fix this by using legacy-serde and supporting both serde 0.9 and serde 1.0. If it's critical.

**Comment by bluss** [comment]
That said, jumping to serde 1.0 is hopefully the sane move in the long term. The version bump to end all version bumps (right? :wink:)
