### ISSUE TITLE
`dot` for IxDyn

### ISSUE THREAD

**Issue by perrier1034** [bluss/rust-ndarray#315]
Now, `dot` is limited to Ix2, but that for IxDyn may be useful (if receiver.ndim() == 2).
How do you think about it?

**Comment by SuperFluffy** [comment]
That sounds like one would need to have `dot` make additional checks at runtime for this to work, and also dynamically determine the resulting dimension.

**Comment by perrier1034** [comment]
yeah, I think you are right. 

Closing.
