### ISSUE TITLE
column standardizing an array?

### ISSUE THREAD

**Issue by Jessime** [bluss/rust-ndarray#317]
I'm trying to port some python/numpy code I have. In numpy, I would be able to do:

```
counts -= np.mean(counts, axis=0)
counts /= np.std(counts, axis=0)
```
where `counts` is a 2D array. What would be the cleanest equivalent? Thanks!

**Comment by SuperFluffy** [comment]
Probably something akin to the following (untested):

```rust
let n = counts.shape()[1] as f64;
for row in counts.genrows_mut() {
    let mean = row.fold(0.0, |acc, x| acc  + x) / n;
    let mut stddev = row.fold(0.0, |acc, x| acc + x.powi(2)) - mean.powi(2));
    stddev = f64::sqrt(stddev / n);
    row -= mean;
    row /= stddev;
}
```

I would not recommend using `ArrayBase::mean`, as that one requires additional allocations in all cases.

Furthermore, this is probably not the most efficient way of doing things. You can probably calculate the expectations `E[x]` and `E[x^2]` in one go. Also I didn't take care of numerical stability.

**Comment by Jessime** [comment]
This code isn't quite behaving as I would expect (and I'm pretty new to Rust, so I'm having trouble debugging). For starters, I'd like to apply this over columns, so I'm doing:

```rust
for mut col in counts.gencolumns_mut() {
    let (mut mean, mut stddev) = col.fold((0.0, 0.0), |acc, x| (acc.0 + x, acc.1 + x.powi(2)));
    mean /= n;
    stddev = f32::sqrt( (stddev - mean)/n );
    col -= mean;
    col /= stddev;
}
```

This runs, but when I do, 

```rust
let means = counts.mean((Axis(0)));
println!("Means: {:?}\n", means);
```
I would expect to see 0's (or approximate 0's), but in my test case, I get all positive floats instead.

**Comment by SuperFluffy** [comment]
That's because `counts.mean((Axis(0))` calculates the mean from “left to right” if you wish - `Axis(0)` is that axis which points in the direction of a row. See the image under the [`ArrayBase::split_at` documentation](http://bluss.github.io/rust-ndarray/master/ndarray/struct.ArrayBase.html#method.split_at) to understand the notation.

Give `counts.mean((Axis(1))` a shot.

**Comment by Jessime** [comment]
Hopefully I'm not going crazy here, but maybe I am.

`counts.shape()` gives me `[5, 16]`. That means 5 rows and 16 columns, right? If I do `counts.mean((Axis(0))`, I get a 1D array of length 16, which is exactly what I would expect. But, if I do `counts.mean((Axis(1))`, I instead get a 1D array of length 5, one for each row, which I don't want. 

In my version of the code that you wrote, I want `col`, `mean` and `stddev` to all have a length of 16. 

---
To your note about performance, I spend most of my time (earlier in my program) iterating over the rows. It isn't until the last step (the normalization we're discussing here), that I want to iterate over columns. I haven't had a change to benchmark yet to see if reshaping is worthwhile.

**Comment by Jessime** [comment]
Got it!!

```rust
let n = counts.shape()[0] as f64;
for mut col in counts.gencolumns_mut() {
    let mean = col.fold(0.0, |acc, x| acc  + x) / n;
    let mut stddev = col.fold(0.0, |acc, x| acc + (x - mean).powi(2));
    stddev = f64::sqrt(stddev/n);
    col -= mean;
    col /= stddev;
}
```
I had to fold twice because I needed the mean to calculate the stddev correctly. 

Thanks for your help!

**Comment by bluss** [comment]
@Jessime Hi. Just to show that they really can be quite similar, it is possible to use broadcasting the same way as in Python:

```rust

#[macro_use]
extern crate ndarray;

use ndarray::prelude::*;

fn std1d(a: ArrayView1<f64>) -> f64 {
    let n = a.len() as f64;
    if n == 0. { return 0.; }
    let mean = a.scalar_sum() / n;
    (a.fold(0., |acc, &x| acc + (x - mean).powi(2)) / n).sqrt()
}

fn std(a: &Array2<f64>, axis: Axis) -> Array1<f64> {
    a.map_axis(axis, |column| std1d(column))
}

fn main() {
    // "recreating the following"
    // counts -= np.mean(counts, axis=0)
    // counts /= np.std(counts, axis=0)

    let mut data = array![[-1., -2., -3.],
                          [ 1., -3.,  5.],
                          [ 2.,  2.,  2.]];

    println!("{:8.4}", data);
    println!("{:8.4} (Mean axis=0)", data.mean(Axis(0)));

    data -= &data.mean(Axis(0));
    println!("{:8.4}", data);

    data /= &std(&data, Axis(0));
    println!("{:8.4}", data);
}
```

**Comment by bluss** [comment]
My column standardize code is an example in the repository now. We're going to add a `std` method sooner or later, and the question is answered.

**Comment by AaronRocinante** [comment]
Why don't add these methods as part of the struct?

**Comment by AaronRocinante** [comment]
I'm trying to do `data -= &data.mean(Axis(0));` but I get the following `thread 'main' panicked at 'ndarray: could not broadcast array from shape: [331476] to: [331476, 5326]'`
What should we do to make the mean vector broadcastable? Thanks

**Comment by jturner314** [comment]
I'm not sure what's going on for you. Are you sure you're taking the mean over axis 0 and not axis 1? This example works for me with the latest version of `ndarray` (0.12.1):

```rust
extern crate ndarray;

use ndarray::prelude::*;

fn main() {
    let mut data = Array2::<i32>::zeros((3, 4));
    data -= &data.mean_axis(Axis(0));
}
```

Can you provide more details?
