### ISSUE TITLE
Support output array for `dot`.

### ISSUE THREAD

**Issue by cristicbz** [bluss/rust-ndarray#323]
I tried to look really hard in the issues and docs and was not able to find this. I'm thinking something like `dot_into(&self, rhs: &Rhs, out: &mut Output)` added to `linalg::Dot`. Right now it seems to me like it's impossible to remove all allocations from an dot-based SGD implementation of logistic regression.

I'd be happy to try and implement this, if people think it's a good idea (and there isn't some other solution already out there).

**Comment by SuperFluffy** [comment]
Depending on your needs, you could work around it by using `xGEMM` or `xGEMV`. Of course it is then necessary to ensure yourself that the arrays are contiguous.

I am not sure about @bluss' opinion on this, but looking at the codebase I think waiting for integer generics among other things would make linear algebra a lot easier.

**Comment by cristicbz** [comment]
I somehow didn't see the `general_mat_mul` function, really sorry! I had searched for `gemm` in the docs thinking there might be a lower level wrapper.

I'll close this issue, though it might still be a good idea of providing this as a method on `linalg::Dot` to work generically on vectors and matrices etc and make it (maybe?) more discoverable.

**Comment by bluss** [comment]
Thanks, that clears it up. Yes, why not?
