### ISSUE TITLE
Trailing comma in `s!` argument list doesn't compile

### ISSUE THREAD

**Issue by jplatte** [bluss/rust-ndarray#324]
I've had rustfmt-nightly (pretty sure the latest legacy rustfmt version behaves the same here though) reformat my use of `s!` so that it had a trailing comma. Here is the error in question, also containing the code snippet that triggered it:

```rust
error: expected expression, found `@`
   --> src/dungeon.rs:291:32
    |
291 |                       .slice_mut(s![
    |  ________________________________^
292 | |                         (x * mult) as isize..((x + 1) * mult + 1) as isize,
293 | |                         (y * mult) as isize..((y + 1) * mult + 1) as isize,
294 | |                     ])
    | |_____________________^
    |
    = note: this error originates in a macro outside of the current crate
```

It would be nice if trailing commas were allowed.

**Comment by bluss** [comment]
I agree that it would be nice to accept a trailing comma, but I think it's very weird that rustfmt would do this. Especially that we don't have really *nice* way to accept trailing commas, just ugly hacks.

**Comment by bluss** [comment]
Fixed, but I register my complaint that there is no nice way to fix this in macros :smile: -- if we use `$(,)*` to avoid duplicating a rule, we admit multiple trailing commas, which is again inconsistent with other Rust syntax.
