### ISSUE TITLE
Parallel (and indexed) equivalent for azip macro: par_azip!()

### ISSUE THREAD

**Issue by msiglreith** [bluss/rust-ndarray#326]
We currently have `azip!` as utility macro for zipping.
With the introduction of ndarray-parallel it would be interesting to provide an additional macro, which would employ parallel iterators internally. For example:
```rust
// snippet from grid based discrete exterior calculus
azip_par!(
    mut edge (&mut edges.1),
    v0 (vertices.slice(s![..-1, ..])),
    v1 (vertices.slice(s![1.., ..]))
 in { *edge = v1 - v0; });
```
The implementation for this macro is basically the same as for `azip!` but using `par_apply` instead of `apply` after zipping.

Additionally, I've been playing around with an parallel indexed version (also implemented):
```rust
// particle simulation substep
azip_indexed_par!(
    lambda_i (lambdas),
    pos (positions),
    mut delta_pos (delta_pos)
index i in {
    // Calculate delta_p
    let cell = if let Some(cell) = grid.get_cell(&pos) { cell } else { return };
    *delta_pos = VectorN::<T, U2>::zero();
    grid.for_each_neighbor(cell, 1, |j| {
        if j == i { return }
        let diff = pos - positions[j];
        *delta_pos += diff * (masses[j] * (lambda_i + lambdas[j]) * spiky.grad_w(pos.distance(positions[j])));
    });
    *delta_pos /= rest_density;
});
```
The interesting part is here the `index i` addition, which specifies a new index variable.
I think it's also worth to mention that these macros are also *really useful* outside of ndarray (the mentioned indexed example uses `Vec` for storing particle data)

Thoughts?

**Comment by bluss** [comment]
Sure, seems very logical. I think the most consistent name is using a par_ prefix, just like rayon likes to do across the board.

I've tried adding simple index support to azip, but didn't find a perfect way for it yet. If you've solved that, I'd love to see it.

**Comment by bluss** [comment]
One thought is that `azip!` was my rather immediate reaction to the Zip thing, trying to make it more usable. With more usage, I got used to Zip and don't feel the need of azip as direly. It's still a shorter syntax, less repetition, but it's a custom and has its own quirks.

What do you think?

**Comment by bluss** [comment]
In particular, the "a" and "mut b" shorthand was added before Zip/azip was generalized to producers, so it immediately became a bit more inconsistent. They are fine for elementwise producers and weird for others.

**Comment by msiglreith** [comment]
> I think the most consistent name is using a par_ prefix, just like rayon likes to do across the board.

Seems reasonable!

> One thought is that azip! was my rather immediate reaction to the Zip thing, trying to make it more usable. With more usage, I got used to Zip and don't feel the need of azip as direly. It's still a shorter syntax, less repetition, but it's a custom and has its own quirks.

I like the `azip!` macro as it's easier to read imo, especially something like `elem (elements)`. (also a bit less error prone as element and storage names are next to each other).

Yesterday I found [multizip](https://docs.rs/itertools/0.6.0/itertools/fn.multizip.html) and I could image this being an interesting alternative to the azip syntax, but I'm unsure if it's possible to adopt this to nadarray+rayon (I'll try it out in the next few days).

Thanks for the feedback so far!
