### ISSUE TITLE
Some clarification.

### ISSUE THREAD

**Issue by bobogei81123** [bluss/rust-ndarray#335]
I'm not sure whether it is appropriate to ask here, but sorry I couldn't find other.

1. Is there a method to convert a static dimension array to a dynamic dimension array?
   (e.g. `Array2 -> ArrayD`)

2. I notice that dimension 0 means a scalar (a single value), but how to extract the
  value from it? 

Thank you very much.

**Comment by bluss** [comment]
1. Is a method we need to provide
2. Good question, probably never spelled out. The only valid index for a zero dimensional array is a set of zero indices. The values `()` and `[]` (same as `[0usize; 0]`) should both work to access the element by index.

**Comment by bluss** [comment]
Oh and the function `Ix0` can create an Ix0 which you can index the array with as well.

**Comment by bluss** [comment]
`NdIndex` implementations section is the place where this information can be understood, with some puzzling.

https://docs.rs/ndarray/0.10.0/ndarray/trait.NdIndex.html

**Comment by bobogei81123** [comment]
Thank you for the clarification!

**Comment by bobogei81123** [comment]
I've requested a pull request 19a27fb for 1.

**Comment by bobogei81123** [comment]
Also, should there be inverses that `try` to convert `IxDyn` and its corresponding array back to
`IxN` ? If there are, dynamic dimensional arrays could be abstractions of static ones where the number of dimensions has to be resolved in runtime.

**Comment by bluss** [comment]
Yes -- it's a good idea. I've considered `.into_shape()` to be enough, but that one requires the user to specify the exact dimension of each axis to try the conversion.

**Comment by bluss** [comment]
I've considered if an `.into_dimensionality()` (or what it will be called) should be weaker, and convert when possible. Say, a one dimensional array of shape 10 turns into shape 1 × 10 if converted to `Ix2`.  There are still cases that error.

**Comment by bobogei81123** [comment]
So maybe the signature would be
`fn into_dimensionality<D2: Dimension>(self) -> Result<ArrayBase<S, D2>, ShapeError>`
impl for `ArrayBase<S, D>` ?

Then it seems that `.into_dimensionality()` could also be implemented for `IxDyn`, and will has the same function of `.into_dyn()` currently, which is a little duplication. The difference is that the return value of `.into_dimensionality()` has to be wrapped in `Result`. Is it ok to have both this two function implemented?

**Comment by bluss** [comment]
Sure, since into_dyn has no error cases, it seems ideal to let it have its own method. I know into_dyn is not in a release yet, sorry I have a backlog on all the crates I maintain.

**Comment by bluss** [comment]
Fixed
