### ISSUE TITLE
Blas binding should be even better at recognizing compatible memory layouts

### ISSUE THREAD

**Issue by bluss** [bluss/rust-ndarray#340]

**Comment by lloydmeta** [comment]
Just copying what the concrete todo we found in #190 is:

> needs to ignore the stride of the axis that is only length 1

I'm kind of new to the whole linalg lib thing but it seems like I can try to tackle this one (while the code is still fresh in my mind), if that's ok with you?

**Comment by bluss** [comment]
Sure, go ahead. I wouldn't mind some fresh eyes on the blas binding stuff, it's pretty ad-hoc. Feel free to discuss with me on irc in #rust-sci or somewhere else; I might be there if we are lucky enough to be online at the same time.

ndarray has stubbornly turned of it's library-embedded tests ("unit tests") in favour of the tests/ directory but we might want to have embedded tests for this. Depends on the best way one finds for testing it.
