### ISSUE TITLE
Add is_empty to ArrayBase

### ISSUE THREAD

**Issue by iamed2** [bluss/rust-ndarray#353]
I found myself expecting this function while writing array code. Would this make sense to have? I'm totally willing to make a PR if you can point me to the best place to implement. I was thinking the best way would be to add a method to `Dimension` checking if any of the axes are 0, but maybe there is a better way?

**Comment by bluss** [comment]
Sure go ahead! Checking Len seems simple enough, we can optimize it later.

Arasys don't grow but we have slicing so there is dynamic sizing going on, so is empty makes sense in particular for views.
