### ISSUE TITLE
Support trailing comma in array! macro

### ISSUE THREAD

**Issue by samueltardieu** [bluss/rust-ndarray#357]
When using `rustfmt`, it sometimes adds a trailing comma when reformatting, as in (produced by `rustfmt`):

``` rust
    let distances = array![
        [90, 75, 75, 80],
        [35, 85, 55, 65],
        [125, 95, 90, 105],
        [45, 110, 95, 115],
    ];
```
This does not compile:

```
error: unexpected end of macro invocation
  --> tests/kuhn_munkres.rs:46:27
   |
46 |         [45, 110, 95, 115],
```
Other similar macros such as `vec![]` support those trailing commas.

**Comment by bluss** [comment]
Thanks. We could add trailing comma support on its own merit, but not because rustfmt is buggy like this.

**Comment by samueltardieu** [comment]
Well, this is part of the `rust` style guide: if an enumeration in brackets, or a `where` clause, is formatted so that the closing delimiter (or the opening block of the function for a `where` clause) is on the next line, then a trailing comma is added. This is a design choice. The trailing comma is not added if the closing delimiter is on the same line.

So we have

``` rust
let d1 = array![
  [1, 2, 3, 4],
  [5, 6, 7, 8],
];
let d2 = array![[1, 2, 3, 4], [5, 6, 7, 8]];

**Comment by bluss** [comment]
I wouldn't be negative if macro_rules had an easy way to support optional trailing commas.
