### ISSUE TITLE
Is there a way to make so that an array becomes Static?

### ISSUE THREAD

**Issue by PhdTrollSlayer** [bluss/rust-ndarray#359]
I want to make so an 3x3 array can be access in another function.
Sorry if this is a noob question...

**Comment by bluss** [comment]
ArrayViews could be used over static data, but we need const functions first (which we don't have in stable Rust). So I don't see a way right now. You can use a static plain rust array and make an array view over it in the function.

**Comment by bluss** [comment]
I wonder if this has been resolved? It's not entirely satisfactory I realize, that we can't really make an array static. But we can convert a &[[T; 3]; 3] into an arrayview with basically zero cost (see function aview2).

**Comment by bluss** [comment]
I guess this question has been answered.
