### ISSUE TITLE
Segfault in ArrayBase::from_shape_fn()

### ISSUE THREAD

**Issue by jturner314** [bluss/rust-ndarray#361]
The following program causes a segfault with `ndarray` 0.10.8:

```rust
extern crate ndarray;

use ndarray::prelude::*;

fn main() {
    let a: Array2<f64> = ArrayBase::from_shape_fn((1, 0).f(), |_| 0.);
}
```

**Comment by jturner314** [comment]
As far as I can tell, this is fixed by changing [line 215 of `src/indexes.rs`](https://github.com/bluss/rust-ndarray/blob/0.10.8/src/indexes.rs#L215) from
```rust
has_remaining: zero != dim,
```
to
```rust
has_remaining: dim.size_checked() != Some(0),
```
I can submit a PR with this change (and add some tests in `tests/array-construct.rs` to catch this in the future), but it would be nice for someone to check that this is the correct fix.

**Comment by bluss** [comment]
Is the same true for (0, 1) and (0, 1).f() ?

**Comment by bluss** [comment]
It seems like the right fix.

**Comment by jturner314** [comment]
`(0, 1)` does not segfault. `(0, 1).f()` does segfault.

As far as I can tell, the issue is that the iterator returned by `indices_iter_f()` has the correct `size_hint()` but is an infinite loop if the shape has nonzero elements and has size zero (e.g. `(0, 1).f()`, `(1, 0, 1).f()`, etc.) . As a result, the `from_shape_fn()` constructor allocates enough memory according to `size_hint()`, but tries to write outside the allocated memory since the loop does not end. The fix is to make `indices_iter_f()` account for the fact that the shape can have nonzero elements but still have zero size.

I'll submit a PR with the fix.

**Comment by bluss** [comment]
It seems like it would be good to have some randomized testing. Thanks for finding and fixing this, it's in a less used and newer code path (f-order), but it was an oversight when the new iterator was implemented.

The indices iterators are "trusted" to be exact length by the code that's allocating a sequence from them in src/iterators/mod.rs.
