### ISSUE TITLE
`.sum_axis()` without new allocation possible?

### ISSUE THREAD

**Issue by fkjogu** [bluss/rust-ndarray#378]
Methods like `.sum_axis()` allocate a new array for their result. Is is possible to prevent that?
Say, if I have a hot loop, where I sum over an axis of a big array. Then a lot allocations are happening. How can I reuse a preallocated array for the result?

**Comment by bluss** [comment]
Hi, it's not possible to prevent in those methods. You have `Zip` (and its macro interface `azip!()`) which should make it relatively easy to write good custom array computations without indexing.

There's an example that matches your question in the documentation -- find Example 2 in the example block in https://docs.rs/ndarray/0.10.12/ndarray/struct.Zip.html


We can adapt that example to sum over arbitrary axis using the lanes producer:

*Given an array `a`, write the sum of each row/col into an array `sums`*

```rust
// in this example I'm still assuming that the input array is 2D
let a = unimplemented!(); // The given array.
let axis = Axis(1); // axis to sum over
let mut sums = Array1::zeros(a.len_of(Axis(0)));  // use the len of the other axis

Zip::from(&mut sums)
    .and(a.lanes(axis))
    .apply(|s, lane| {
        *s = lane.scalar_sum();
    });
```

The producer `lanes` is just a generalization of `genrows/gencolumns`.

**Comment by fkjogu** [comment]
Sweet! `Zip` is a real working horse. I have to try that.
