### ISSUE TITLE
inner_iter()?

### ISSUE THREAD

**Issue by nilgoyette** [bluss/rust-ndarray#379]
I think it's more a question than an issue but I don't know where to ask. I'm trying to write 3D/4D nifti images using the data from a `Array<T, D>` I started using

    for e in image.iter() { writer.write(e); }

but I realized that ndarray iterates on the "outer" dimension first. iter: `corresponds to increasing the last index first: 0, ..., 0, 0; 0, ..., 0, 1; 0, ...0, 2 and so on.` So now I write

    for z in 0..depth {
        for y in 0..height {
            for x in 0..width {
                write( *data.uget((x, y, z)) )

Of course, this won't work for a 4D image. The single loop with `iter` was much more convenient. Is there a way to iterate on all values with a single loop using a "first index first"?

**Comment by bluss** [comment]
Of course in ndarray's own terminology, it's inner is the last axis, the one that is the "innermost loop".

This is documented and can be relied on for .iter(). You take advantage of it readily here by using .t().iter(), that's the iterator with axes reversed. t() works on all dimensionalities.

**Comment by nilgoyette** [comment]
Haha, wow, I never thought about transpose! Thank you. I'll close this issue.

It wasn't clear to me and it may be unclear to others too. I think it should be documented in the [iter section](https://docs.rs/ndarray/0.10.12/ndarray/struct.ArrayBase.html#iter-and-iter_mut) because that's where people go, I think, when they want to iterate.

**Comment by bluss** [comment]
Yeah certainly, it could be mentioned there or in the [section about iteration and index order](https://docs.rs/ndarray/0.10.12/ndarray/struct.ArrayBase.html#indexing-and-dimension) maybe. Whoever posts the PR can decide.
