### ISSUE TITLE
Parallel for_each_with or map_with with indexing

### ISSUE THREAD

**Issue by nilgoyette** [bluss/rust-ndarray#384]
I have this code, which is working quite well.

    Zip::indexed(&mut output_image).par_apply(
        |(i, j, k), o| *o = self.process_block(i, j, k));

My problem is that `process_block` needs a big vector to do its job and this code is allocating it millions of times. Someone told me that I need to use `for_each_with` or `map_with` to avoid this problem. I know I can use them with `into_par_iter()` but then I lose the index.

    input_image.into_par_iter().map_with( ... ); // index?

Is there a way to have both? I can't find any example that shows how to do it.

**Comment by bluss** [comment]
It's a missing feature, good that you brought it up.

**Comment by bluss** [comment]
Let's make it more accessible.

It should be available to you using `(Zip:: ...)..into_par_iter().for_each_with(...)`. Does that work for you?

**Comment by nilgoyette** [comment]
Yes, perfect. I wasn't aware that I could access all `rayon` tools using `.into_par_iter()` after a call to Zip! Thank you.

I have another [somewhat related] question, if I may.

    You'll need a big chunk of data (or an expensive operation per data point) to gain from parallelization.

I already have a big gain from parallelization but the computation for each voxel takes a tiny amount of time, like 0.03ms. Should I give columns or even slices to each thread?

**Comment by bluss** [comment]
Ah that's cool. 30µs is not *that* short of a time. The splitting in the parallel iterator should already handle the size of the chunks of the array that end up in each thread (or thread pool job), so it's great if you don't need to tweak further.

I think the tasks that too cheap to gain from parallelism are things like `element += 1` etc, so something much closer to single arithmetic operations per element. (As usual such operations should first be SIMD-parallelized before being thread-parallel; ndarray tries its best to support both.)

**Comment by nilgoyette** [comment]
Cool. I worried that passing to the next voxels was heavy for the threads. Thank you.
