### ISSUE TITLE
Allow `gemv` optimizations for column-major matrices

### ISSUE THREAD

**Issue by maciejkula** [bluss/rust-ndarray#406]
Currently, when running a matrix-vector multiply, BLAS `gemv` is called only if the matrix operand is row-major: https://github.com/bluss/rust-ndarray/blob/5daa294750f640fbe5195fc144900a7afcea82ce/src/linalg/impl_linalg.rs#L581

It would be quite useful to allow `gemv` optimizations also in the case of column-major arrays, passing the appropriate arguments down to BLAS.

I could have a look if you like?

**Comment by bluss** [comment]
Sure, sounds great
