### ISSUE TITLE
Evaluate Scalar operands. K @ A and A @ K where K is scalar, A an array.

### ISSUE THREAD

**Issue by bluss** [bluss/rust-ndarray#41]
We need user feedback on scalar ops.

**Comment by nilgoyette** [comment]
Isn't this task [done](https://docs.rs/ndarray/0.11.0/ndarray/struct.ArrayBase.html#binary-operators-with-array-and-scalar)? If not, can you clarify what you meant?

**Comment by bluss** [comment]
Yes let's close this, the API is fairly established. The docs contain the gritty details.
