### ISSUE TITLE
Constructor with specific stride

### ISSUE THREAD

**Issue by vbarrielle** [bluss/rust-ndarray#59]
In some cases it can be nice to be able to specify a specific stride when constructing a new array (for instance to wrap over foreign data).

**Comment by vbarrielle** [comment]
For safety issues, this probably requires being able to tell if the given dimensions and strides are compatible with the given vector or slice.

**Comment by bluss** [comment]
And / or providing an `unsafe` constructor too

**Comment by vbarrielle** [comment]
Indeed. I'd say and, because it seems possible to provide a safe one that 
panics on improper input.
As far as I can tell right now, a requirement would be that all strides are 
positive, and that the last addressable element falls inside the length of the 
vector/slice.

I can try and implement that tomorrow if that suits you.

**Comment by bluss** [comment]
With that restriction it should be easy to compute yes.

If you have a slice you can already produce an array view and reslice it (aview1, aview1_mut and .slice()), but I guess this is for the case where you have strides already computed from a different representation.
