### ISSUE TITLE
alpha versioning looks problematic with crates.io

### ISSUE THREAD

**Issue by vbarrielle** [bluss/rust-ndarray#72]
I was trying to make a crate depend on the version 0.4.0-alpha.1 that's on crates.io, but if I specify the dependency as `ndarray = "0.4"` I get the cargo error `unable to get packages from source`, and if I try to put the exact version number cargo errs out telling me it can't parse the cargo.toml.

However this works fine when specifying the dependency via git.

So maybe alpha versions should not be uploaded to crates.io as it seems they can"t be used from there.

**Comment by bluss** [comment]
I've managed to use it, exact version "0.4.0-alpha.1". Does that work?

**Comment by bluss** [comment]
I guess alpha versioning is unconventional. I want to have the new code out there before we make a new point release.

**Comment by vbarrielle** [comment]
I've tested a bit more, the exact version "0.4.0-alpha.1" works with a nightly setup, but not on beta or stable.

**Comment by bluss** [comment]
> version-wise, It's expected that "0.4" does *not* match the alpha version. `0.4.0` is a greater (later) version than any `0.4.0-alpha` release.  I guess this is something that's fixed in cargo nightly.

Will fix using the other issue #73
