### ISSUE TITLE
"0.4.0-alpha.1" on cargo.io fails to download, please reup with new cargo

### ISSUE THREAD

**Issue by SuperFluffy** [bluss/rust-ndarray#73]
Building version `0.4.0-alpha.1` with the dependency `ndarray = "~0.4.0"` in `Cargo.toml` gives the following error:

````
% cargo build --verbose
unable to get packages from source

Caused by:
  failed to unpack package `ndarray v0.4.0-alpha.1`

Caused by:
  No such file or directory (os error 2)
zsh: exit 101   cargo build --verbose
````

Apparently this was an issue with the recent cargo build and is now fixed. According to [this comment]( https://github.com/rust-lang/cargo/issues/2326#issuecomment-176565809), crates for which this problem still occurs should be reuploaded with a recent cargo version.

You put `ndarray` onto `crates.io` just a few days before this error report was posted, so I think this might be related.

**Comment by vbarrielle** [comment]
Looks like the same problem as #72. Before it's fixed maybe you can use the same workaround as me, ie compiling under nightly with the dependency as `ndarray = "0.4.0-alpha.1"`.

**Comment by bluss** [comment]
Thanks for reporting this issue, I'll upload a new version.

**Comment by bluss** [comment]
version-wise, It's expected that "0.4" does *not* match the alpha version. `0.4.0` is a greater (later) version than any `0.4.0-alpha` release.

**Comment by bluss** [comment]
`0.4.0-alpha.2` has been released.
