### ISSUE TITLE
BLAS: Investigate validity of shared / mutable array views with interleaved data

### ISSUE THREAD

**Issue by bluss** [bluss/rust-ndarray#79]
Consider this case:

> If you're interested, a tricky question remains, imagine a 4 x 4 matrix in row major order. The columns of the matrix are technically both F-order and C-order since they are one dimensional (but with a leading dimension of 4).
> 
> Anyway, adjacent columns do not overlap, but their memory interleaves very closely. Is this compatible with blas? :smile:

**Comment by vbarrielle** [comment]
I've had a look at the cblas documentation at http://www.netlib.org/blas/blast-forum/cinterface.pdf

This excerpt seems relevant (annex B.2.7):

> unless specified otherwise, only input-only arguments (specified with the const qualifier) may be legally aliased on a call to the C interface to BLAS.

As methods such as `gemm` in cblas require `const` input arguments, I suppose there is no problem with eg computing A^T * A with aliasing on the input.

**Comment by vbarrielle** [comment]
And this also forbids mutable aliasing. Which is quite nice since it's exactly what rust wants too :)

**Comment by bluss** [comment]
Here's a tricky case though. Using low sizes to simplify.

Consider the 2x2 array in row major memory order.

Data is: `1., 2., 3., 4.`
Logical layout is:

```rust
[[1.  2.],
 [3.  4.]]
```

ndarray allows getting the first column as a mutable view and second column as an immutable view.

Column 0: `1., 3.`
Column 1: `2., 4.`

The problem is that the columns don't alias in the rust sense, but their data interleaves. Is this allowed by blas? Suppose one of the columns is a mutable argument and the other is a constant argument.

**Comment by vbarrielle** [comment]
It looks tricky, but I don't think any reasonable implementation of a blas function can be a problem. In fortran, the compiler is free to assume that pointers do not alias,  but there would need to be a bug in the implementation to access the same element in both the const pointer and the mutable one.
There might be an issue if the compiler tried to insert vectorisation, but I don't see why the optimiser would do that.

**Comment by vbarrielle** [comment]
However I'm not sure there are blas functions which accept non-contiguous vectors, I've seen stride parameters for matrices but not for vectors in eg gemv: http://www.netlib.org/lapack/explore-html/d7/d15/group__double__blas__level2.html#gadd421a107a488d524859b4a64c1901a9

**Comment by bluss** [comment]
INCX and INCY are the stride parameters for the vectors there actually.

**Comment by vbarrielle** [comment]
Ok I had missed that. Here's an interesting data point: numpy will not allow the equivalent of your example.

```python
import numpy as np
a = np.random.rand(2, 2)
b = np.random.rand(2, 2)
b.dot(a[:, 0:1], out=a[:, 1:2])
```

```
ValueError: output array is not acceptable (must have the right type, nr dimensions, and be a C-Array)
```

So the numpy developers had an issue with that case.

**Comment by vbarrielle** [comment]
Further investigating numpy's behaviour, it looks like they did not allow out parameters to have a storage different than C-order contiguous for simplicity reason (they have a `gemv` wrapper that requires the output stride to be 1).

I've tested directly against blas using C, and the following program:

```C

#include <stdio.h>
#include <cblas.h>

int main()
{
  float a[] = { 1., 2., 3., 4.  };
  float b[] = { 1., 1., 1., 1.  };

  cblas_sgemv(CblasColMajor, CblasTrans, 2, 2, 1., &b[0], 2,
              &a[0], 2,
              0., &a[1], 2);

  printf("%f %f\n%f %f\n", a[0], a[1], a[2], a[3]);

  return 0;
}
```

will print the correct output, ie:
```
1.000000 4.000000
3.000000 4.000000
```

Now sadly this does not mean that any blas implementation will yield the correct output, but that's the output of the reference blas implementation (libblas3 on my ubuntu system claims to be the reference fortran 77 implementation found at netlib).

**Comment by bluss** [comment]
Thanks for looking. It does look pretty good then.

**Comment by bluss** [comment]
This was addressed!
