### ISSUE TITLE
Strongly typed `Axis` arguments

### ISSUE THREAD

**Issue by bluss** [bluss/rust-ndarray#91]
We could have strongly typed `Axis` arguments (instead of current usize).

It even allows mixing dynamically bounds checked axis numbers and statically checked ones:

`.subview(Axis(0), 1)` vs. `.subview(Axis0, 1)` would both be possible at the same time.

**Comment by vbarrielle** [comment]
Yes that's really a nice feature to have, imo it improves readability and prevents some mistakes. `Axis0` would be exposed as a constant?

**Comment by bluss** [comment]
Yes. Using generics is unfortunate in one way, since it makes the interface seem more complicated. But it also enables static checking. I've tested this out at some point, and I think it works.

**Comment by bluss** [comment]
Oh I think it requires n² impl blocks where n is the number of dimensions supported though (We have up to 12-tuples).

**Comment by vbarrielle** [comment]
Maybe macros can help on that point, but I wouldn't know, I've not written many macros yet.

**Comment by bluss** [comment]
Fixed by #97
